### ISSUE TITLE
[Bug Report] Seems a new discord update changed some display stuff

### ISSUE THREAD

**Issue by ClarusNox** [ClearVision/ClearVision-v6#146]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

The change relates to how discord channels look when they have unread messages, now with the theme they barely stand out from read channels.

### Reproduction Steps

```bash
1.No steps, display just changed after an update
2.
3.
...
```

### Screenshots

```bash
https://imgur.com/3u5mUEx
```

**Comment by LinUwUxCat** [comment]
As a temp fix, you can use this 
```css
.wrapper-NhbLHG.modeUnread-3Cxepe .iconContainer-21RCa3 .icon-2W8DHg{
  color: var(--channel-unread);
  filter: drop-shadow(0 0 3px);
  opacity: 1;
}
.wrapper-NhbLHG.modeUnread-3Cxepe .name-28HaxV{
  color: var(--channel-unread);
  text-shadow : 0 0 3px;
}
```
