### ISSUE TITLE
[Feature Request] add support for Spotify controller UI

### ISSUE THREAD

**Issue by dada878** [ClearVision/ClearVision-v6#172]
### Did You Search Other Suggestions?

- [X] I have checked if this feature request exists already

### Is your feature request related to a problem?

I used this Vencord plugin with the ClearVision theme, but it's seems not to work very well.
https://vencord.dev/plugins/SpotifyControls

![image](https://github.com/ClearVision/ClearVision-v6/assets/37009584/7f0f52e6-8e25-42b7-875b-0902d98cd89b)

### Screenshots and/or description of the feature request.

I tried to add some css script to it, and then it worked better, I hope you can add this to the theme.

![image](https://github.com/ClearVision/ClearVision-v6/assets/37009584/fd654a96-96a5-4105-b15f-7eb79d9570db)
```css
.theme-dark #vc-spotify-player {
    background: transparent;
}

#vc-spotify-player {
    border-top: 1px solid var(--background-modifier-accent);
}
```

### Why does the theme need this?

I think... maybe there are many Spotify users?
