### ISSUE TITLE
[Feature Request] Apply Theme elements to override Mod View

### ISSUE THREAD

**Issue by Zacam** [ClearVision/ClearVision-v6#193]
### Did You Search Other Suggestions?

- [X] I have checked if this feature request exists already

### Is your feature request related to a problem?

This is a feature request for an entirely optional enhancement.

### Screenshots and/or description of the feature request.

To be fair, Server 'Mod View' when selecting a Server Member appears to be trying to render based on the same values as defined by User Profile; in some cases where that is "Default" the result is a glaringly white box (which doesn't happen when viewing said Members profile, either in sidebar or pop-up view).

However, it would be an improvement (since it is actions at a server level) to "override" that behaviour in order to render in-line with the over all Theme.

### Why does the theme need this?

Would allow a more cohesive/blended view throughout the application and be visually less jarring.

**Comment by Leozard** [comment]
Hi! For ClearVision we don't remove custom profile colors cause we don't want to remove or restrict paid features, which includes the mod view.

However you add the code below into your theme file or customcss to to remove the colours from mod view on your own file
```css
.sidebarContianer__623bd .userProfileModalInner__84e47, /* border */
.sidebarContianer__623bd .userProfileOuterThemed_a425f3 { /* background */
	background: transparent;
}
.userProfileInner__8ff35:before { /* dark overlay */
	background: transparent;
}
```
If you need anymore please visit our discord cause we check there more often
