### ISSUE TITLE
channel main color 

### ISSUE THREAD

**Issue by AzuKaOwO** [ClearVision/ClearVision-v6#55]
**Is your feature request related to a problem? Please describe.**
channel main color too glowing

**Describe the solution you'd like**
set the glowing to discord default

**Describe alternatives you've considered**
option i can choose glowing value

**Additional context**
![image](https://user-images.githubusercontent.com/60112822/122194409-b52ce780-ce95-11eb-8c2a-713cdaa17c38.png)

**Comment by Leozard** [comment]
I don't understand what ur asking?

**Comment by NyxIsBad** [comment]
This is rather easily resolvable with custom css and shouldnt be something in regards to the main theme. They want to be able to control the text shadow / glow in text
```css
.wrapper-2jXpOf.modeUnread-1qO3K1 .content-1x5b-n .mainContent-u_9PKf .name-23GUGE,.wrapper-2jXpOf.modeUnread-1qO3K1 .content-1x5b-n .mainContent-u_9PKf .icon-1DeIlz{
  filter: none !important;
  text-shadow: none !important;
}
```
This snippet is widely available in the server and by tweaking values for these two properties you can control the amount of glow yourself
