### ISSUE TITLE
Add backgroudn for metion text.

### ISSUE THREAD

**Issue by austinbabe** [ClearVision/ClearVision-v6#61]
**Is your feature request related to a problem? Please describe.**
not, didn't relate any problem.

**Describe the solution you'd like**
Hope there were different background-color of the mentioned text and the normal one.
https://i.imgur.com/vMuIuF1.png

**Comment by Enderhoang** [comment]
I found out that it is easily editable by using this in the Custom CSS. It should be a relatively easy fix in the main css file with support for custom color in the theme itself.
```css
.markup-2BOw-j .wrapper-3WhCwL {
  background-color: (insert your color);
}
```
