### ISSUE TITLE
[Bug Report] Message components buttons not colored

### ISSUE THREAD

**Issue by 20Alexanderxx** [ClearVision/ClearVision-v6#84]
### Did You Search Other Issues?

- [X] I have checked other issues

### Describe The Bug

the buttons from the discord message components aren't colored accordingly to discord. 

### Reproduction Steps

```bash
1. get some buttons i guess
2. see the missing buttons: primary, secondary, success and link
3.
...
```

### Screenshots

Buttons with ClearVision: 
![q1TISnx](https://user-images.githubusercontent.com/89459209/151669217-80c9a856-fc19-40f3-a353-649a22bcda56.png)

Buttons without ClearVision: 
![JpPeY1N](https://user-images.githubusercontent.com/89459209/151669232-79104f89-2a53-4370-9ecb-549b7508d1d1.png)

### Additional Context

i saw the old bug report of the topic, but this is a few months old and the buttons are getting more and more importance, so if it is noww working as intended, it would be great to have an option to enable custom button colors or stay with the main one

**Comment by NyxIsBad** [comment]
We'll implement success, although I think that secondary and link are not necessary for now

**Comment by Leozard** [comment]
success button will be looked into, other buttons are working as intended

**Comment by 20Alexanderxx** [comment]
i think secondary buttons are important, as they e.g show some things that are more important than others like in our example:
![image](https://user-images.githubusercontent.com/89459209/151673242-e285e41d-28a3-4b6d-a825-eb03994c6130.png)
they show what categories are required and still need some working...

**Comment by NyxIsBad** [comment]
First, let's remove Link from consideration because I don't have a variable for that and I think it's pretty obviously indicated by the link icon ~

As for secondary, while I do see your point, I believe that the usage of secondary is minimal enough that it's not worth the effort of fixing. It's effort because we don't have a secondary main color - we only have main color, success, and danger defined as accent colors. There just wasn't enough usage for a secondary main color, and we won't use the default discord grey for this.

While we could also theme this using some spin off of main color by applying some filter or some one off color, this would be bad precedent and design (only exists in one place, I'd rather not have isolated one off usage of colors). 

Using these lines of reasoning, I am going to decline to theme link and secondary buttons. Of course, if usage of secondary buttons becomes significant enough that this matters, this is certainly worth reconsidering.

**Comment by NyxIsBad** [comment]
I will leave this issue open for discussion,

Success was added in https://github.com/ClearVision/ClearVision-v6/commit/541d79f7233d5698fa40656fb2ff29f26a6fe27d

**Comment by 20Alexanderxx** [comment]
Ok, I understand your point. 
Would it be obvious in the config, on how to add this for myself if I want to do so?
In that case it seems like a solution that would satisfy both sides?

**Comment by NyxIsBad** [comment]
> Ok, I understand your point. Would it be obvious in the config, on how to add this for myself if I want to do so? In that case it seems like a solution that would satisfy both sides?

If you want to mess with the repo directly, you're going to want to edit `button.scss`

See line 32 for the format, secondary buttons are class `%buttonFilledGrey` or `.lookFilled-yCfaCM.colorGrey-2iAG-B`. Example,
```scss
...
%buttonFilledRed {
	background-color: cv("colors.danger");
}
%embedContainer %buttonFilledGreen {
	background-color: cv("colors.success");
}
//This
%embedContainer %buttonFilledGrey {
	background-color: grey;
}
%buttonFilledWhite {
	background: hsla(0, 0%, 100%, .1);
	> %buttonContents {
...
```
If you want to just use custom css,
```css
.container-2sjPya .lookFilled-yCfaCM.colorGrey-2iAG-B {
  background-color: grey; //change this to whatever the color is 
}
```

If you are further unfamiliar with how to edit your own preset/theme/fork of the repo, join our discord support server and I'll help you there, since it's probably not the best place to do this over github issues
